name: CI

on: [issue_comment]

jobs:
  build:

    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: My first step
      if: github.event_name == 'issue_comment' && github.event.action == 'created'
      run: echo ${{ github.event.comment.body }}
